
CREATE TABLE Account (
	AccountID UNIQUEIDENTIFIER NOT NULL,
	LastUpdateUTC DATETIME NOT NULL,

	Username VARCHAR(32) NOT NULL,
	Approved BIT NOT NULL

	CONSTRAINT accPKNClstAccountID PRIMARY KEY NONCLUSTERED (AccountID),
	CONSTRAINT accUniqClstUsername UNIQUE CLUSTERED (Username)
)

CREATE TABLE AccountAccessCode (
	AccountAccessCodeID UNIQUEIDENTIFIER NOT NULL,
	LastUpdateUTC DATETIME NOT NULL,

	AccountID UNIQUEIDENTIFIER NOT NULL,
	AccessCode VARBINARY(128) NOT NULL

	CONSTRAINT aacPKNClstAccountAccessCodeID PRIMARY KEY NONCLUSTERED (AccountAccessCodeID),
	CONSTRAINT aacFKAccountID FOREIGN KEY (AccountID) REFERENCES Account (AccountID),
	CONSTRAINT aacUniqClstAccountID UNIQUE CLUSTERED (AccountID)
)