
CREATE TABLE ACCOUNT (
	AccountID UNIQUEIDENTIFIER NOT NULL,
	accUTCLastUpdate DATETIME NOT NULL,

	accUserName VARCHAR(32) NOT NULL,
	accDisplayName VARCHAR(32) NOT NULL,
	accApproved BIT NOT NULL

	CONSTRAINT accPKNClstAccountID PRIMARY KEY NONCLUSTERED (AccountID),
	CONSTRAINT accUniqClstUserName UNIQUE CLUSTERED (accUsername)
)

CREATE TABLE ACCOUNT_ACCESS_CODE (
	AccountAccessCodeID UNIQUEIDENTIFIER NOT NULL,
	aacUTCLastUpdated DATETIME NOT NULL,

	AccountID UNIQUEIDENTIFIER NOT NULL,
	aacAccessCode VARCHAR(256) NOT NULL

	CONSTRAINT aacPKNClstAccountAccessCodeID PRIMARY KEY NONCLUSTERED (AccountAccessCodeID),
	CONSTRAINT aacFKAccountID FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID),
	CONSTRAINT aacUniqClstAccountID UNIQUE CLUSTERED (AccountID)
)

CREATE TABLE JAM_ADDRESS (
	JamAddressID UNIQUEIDENTIFIER NOT NULL,
	jaUTCLastUpdate DATETIME NOT NULL,

	AccountID UNIQUEIDENTIFIER NOT NULL,
	jaAddressName VARCHAR(32) NOT NULL,
	jaSoftwareIdentifier UNIQUEIDENTIFIER NOT NULL,
	jaPublic BIT NOT NULL

	CONSTRAINT jaPKNClstJamAddressID PRIMARY KEY NONCLUSTERED (JamAddressID),
	CONSTRAINT jsFKAccountID FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID),
	CONSTRAINT jaUniqClstAddressName UNIQUE CLUSTERED (jaAddressName),
)

CREATE TABLE PERMISSION (
	PermissionID UNIQUEIDENTIFIER NOT NULL,
	permUTCLastUpdate DATETIME NOT NULL,

	permName VARCHAR(32) NOT NULL,
	permDescription VARCHAR(256) NULL,
	permParentPermissionID UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT permPKPermissionID PRIMARY KEY (PermissionID),
	CONSTRAINT permFKParentPermissionID FOREIGN KEY (permParentPermissionID) REFERENCES PERMISSION (PermissionID),
	CONSTRAINT permUniqName UNIQUE (permName)
)

CREATE TABLE ACCOUNT_PERMISSION_ASSOC (
	AccountPermissionID UNIQUEIDENTIFIER NOT NULL,
	apUTCLastUpdate DATETIME NOT NULL,

	AccountID UNIQUEIDENTIFIER NOT NULL,
	PermissionID UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT apPKNClstAccountPermissionID PRIMARY KEY NONCLUSTERED (AccountPermissionID),
	CONSTRAINT apFKAccountID FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID),
	CONSTRAINT apFKPermissionID FOREIGN KEY (PermissionID) REFERENCES PERMISSION (PermissionID),
	CONSTRAINT apUniqAccountIDPermissionID UNIQUE (AccountID, PermissionID),
	
	INDEX apIdxClstAccountID CLUSTERED (AccountID)
)