//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAccessCode
    {
        public System.Guid AccountAccessCodeID { get; set; }
        public System.DateTime LastUpdateUTC { get; set; }
        public System.Guid AccountID { get; set; }
        public byte[] AccessCode { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
