//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamLib.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JamServerEntities : DbContext
    {
        public JamServerEntities()
            : base("name=JamServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountPermissionAssociation> AccountPermissionAssociations { get; set; }
        public virtual DbSet<JamAddress> JamAddresses { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<AccountAccessCode> AccountAccessCodes { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
    }
}
