//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permission()
        {
            this.AccountPermissionAssociations = new HashSet<AccountPermissionAssociation>();
            this.Permission1 = new HashSet<Permission>();
        }
    
        public System.Guid PermissionID { get; set; }
        public System.DateTime LastUpdateUTC { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDescription { get; set; }
        public System.Guid ParentPermissionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPermissionAssociation> AccountPermissionAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permission1 { get; set; }
        public virtual Permission Permission2 { get; set; }
    }
}
